name: iOS Build

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Build App
        run: |
          xcodebuild clean build \
          -project ToDos.xcodeproj \
          -scheme ToDos \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation)' \
          CODE_SIGNING_ALLOWED=NO
