name: iOS IPA Build

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Build Archive
        run: |
          xcodebuild clean archive \
          -project ToDos.xcodeproj \
          -scheme ToDos \
          -sdk iphoneos \
          -archivePath build/ToDos.xcarchive \
          CODE_SIGNING_ALLOWED=NO

      - name: Create IPA
        run: |
          mkdir Payload
          cp -R build/ToDos.xcarchive/Products/Applications/ToDos.app Payload
          zip -r ToDos.ipa Payload

      - name: Verify IPA
        run: ls -la

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ToDos-IPA
          path: ToDos.ipa
