name: iOS IPA Build

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Build Archive
        run: |
          xcodebuild clean archive \
          -project ToDos.xcodeproj \
          -scheme ToDos \
          -sdk iphoneos \
          -archivePath ${{ github.workspace }}/build/ToDos.xcarchive \
          CODE_SIGNING_ALLOWED=NO

      - name: Export IPA
        run: |
          mkdir -p ${{ github.workspace }}/build/Payload
          cp -R ${{ github.workspace }}/build/ToDos.xcarchive/Products/Applications/ToDos.app \
          ${{ github.workspace }}/build/Payload/

          cd ${{ github.workspace }}/build
          zip -r ToDos.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ToDos-IPA
          path: build/ToDos.ipa
